---
# handlers file for lemp-server
- name: nginx-service
  service:
    name: nginx
    state: restarted
- name: php-fpm-service
  service:
    name: php8.2-fpm
    state: restarted
- name: mysql-service
  service:
    name: mysql
    state: restarted